# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@2.0.3


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/python:3.10

    working_directory: ~/repo

    steps:
      # Step 1: Obtain repo from GitHub
      - checkout

      # Step 2: restores saved dependency cache if the Branch key template or
      # pyproject.toml files have not changed since the previous run
      # to clear cache increment the deps key by 1 (e.g. deps3)
      # - restore_cache: 
      #     key: &deps2-cache deps2-{{ .Branch }}-{{ checksum "pyproject.toml" }}
      
      # Step 3: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .
            pip install pytest
            pip install tox

      # Step 4: save dependency cache
      # - save_cache:
      #     key: *deps2-cache
      #     paths:
      #       - "venv"

      # Step 5: run tests
      - run:
          name: run tests
          no_output_timeout: 30m
          command: |
            . venv/bin/activate
            tox
